services:
  postgres:
    image: postgres:17
    container_name: estimate-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5499:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
