{{- if .Values.postgres.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "estimate-chart.fullname" . }}-postgres
  labels:
    helm.sh/chart: {{ include "estimate-chart.chart" . }}
    app.kubernetes.io/name: {{ include "estimate-chart.name" . }}-postgres
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/component: postgres
spec:
  type: ClusterIP
  ports:
    - name: postgres
      port: {{ .Values.postgres.service.port }}
      targetPort: postgres
      protocol: TCP
  selector:
    app.kubernetes.io/name: {{ include "estimate-chart.name" . }}-postgres
    app.kubernetes.io/instance: {{ .Release.Name }}
{{- end }}
